---
title: "Regression"
author: "Nathan Tozer"
date: "28/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load('BT.hard.strengths.RData')
load('BT.clay.strengths.RData')
load('BT.grass.strengths.RData')
```

```{r}
# Training Data Set
training.df <- read.csv(file="TrainingDataSet.csv")
training.df <- training.df[-c((37:42))][1:5270,]

# Remove matches that didn't finish, or have mssing information
training.df <- training.df[training.df$Comment == 'Completed',]
training.df <- training.df[training.df$WRank != 'N/A',]
training.df <- training.df[training.df$LRank != 'N/A',]

# Filling un-played sets as 0-0 games won.
for (i in (1:nrow(training.df))){
  
  if (is.na(training.df$W1[i])){
    training.df$W1[i] <- 0
  }
  if (is.na(training.df$W2[i])){
    training.df$W2[i] <- 0
    }
  if (is.na(training.df$W3[i])){
    training.df$W3[i] <- 0
    }
  if (is.na(training.df$W4[i])){
    training.df$W4[i] <- 0
    }
  if (is.na(training.df$W5[i])){
    training.df$W5[i] <- 0
  }
  if (is.na(training.df$L1[i])){
    training.df$L1[i] <- 0
  }
  if (is.na(training.df$L2[i])){
    training.df$L2[i] <- 0
    }
  if (is.na(training.df$L3[i])){
    training.df$L3[i] <- 0
    }
  if (is.na(training.df$L4[i])){
    training.df$L4[i] <- 0
    }
  if (is.na(training.df$L5[i])){
    training.df$L5[i] <- 0
  }
}

training.df.hard <- training.df[training.df$Surface == 'Hard',]
training.df.clay <- training.df[training.df$Surface == 'Clay',]
training.df.grass <- training.df[training.df$Surface == 'Grass',]
```

```{r}
# Importing the results that we wish to predict with our model
test.df <- read.csv(file="TestDataSet.csv")
test.df <- test.df[-c((39:42))]
test.df <- test.df[1:2610,]

# Again we only consider matches that where won by tennis alone
test.df <- test.df[test.df$Comment == 'Completed',]
test.df <- test.df[test.df$WRank != 'N/A',]
test.df <- test.df[test.df$LRank != 'N/A',]

# Filling un-played sets as 0-0 games won.
for (i in (1:nrow(test.df))){
  
  if (is.na(test.df$W1[i])){
    test.df$W1[i] <- 0
  }
  if (is.na(test.df$W2[i])){
    test.df$W2[i] <- 0
    }
  if (is.na(test.df$W3[i])){
  test.df$W3[i] <- 0
    }
  if (is.na(test.df$W4[i])){
    test.df$W4[i] <- 0
    }
  if (is.na(test.df$W5[i])){
    test.df$W5[i] <- 0
  }
  if (is.na(test.df$L1[i])){
    test.df$L1[i] <- 0
  }
  if (is.na(test.df$L2[i])){
    test.df$L2[i] <- 0
    }
  if (is.na(test.df$L3[i])){
    test.df$L3[i] <- 0
    }
  if (is.na(test.df$L4[i])){
    test.df$L4[i] <- 0
    }
  if (is.na(test.df$L5[i])){
    test.df$L5[i] <- 0
  }
}

test.df.hard <- test.df[test.df$Surface == 'Hard',]
test.df.clay <- test.df[test.df$Surface == 'Clay',]
test.df.grass <- test.df[test.df$Surface == 'Grass',]
```

```{r}
# This section calculates various scoring measures for our model

# Prediction accuracy of the model
pred.acc <- function(analysis.df){
  return(sum(analysis.df$IsPredRight)*100/nrow(analysis.df))
}

# Average probability assigned to the actual winner
av.win.prob <- function(analysis.df){
  return(mean(analysis.df$PredProbActualWinner))
}

# Average log probability assigned to the actual winner
av.log.win.prob <- function(analysis.df){
  return(mean(log(analysis.df$PredProbActualWinner)))
}

# Returns a calibration graph of the model
calibration <- function(analysis.df, name){

  p.bins <- seq(from=0, to=1, length.out= 64)
  
  bins <- cut(analysis.df$PredProbActualWinner, breaks = p.bins, include.lowest = TRUE, right = FALSE, ordered_result = TRUE)
  count <- unname(summary(bins))
  
  j <- length(count)
  
  xvals <- seq(from=0.5,to=1,length.out=32)
  k <- length(xvals)
  yvals <- rep(0,length(xvals))
  
  for (i in (1:k)){
    yvals[k+1-i] <- count[j+1-i]/(count[i]+count[j+1-i])
  }
  png(paste('Calibration', name, '.png', sep=""), width=512, height=512)
  scatter.smooth(x=xvals, y=yvals, main= "Model Calibration", xlab="Predicted Probability", ylab="Probability of Prediction Being Correct", cex.main=2, cex.axis=1.6,cex.lab=1.6, ylim=c(0.5,1))
  lines(xvals,xvals,col='red')
  dev.off()
}

# Return on investment when placing a pass-line bet when our model is more confident then the bookmakers
roi <- function(analysis.df){
  new.analysis.df <- analysis.df[!is.na(analysis.df$BookiesProbActualWinner),]
  M <- nrow(new.analysis.df)
  spent <- 0
  won <- 0
  
  for (i in (1:M)){
    if (new.analysis.df$IsPredRight[i] == 1){
      if (new.analysis.df$PredProbActualWinner[i] > as.numeric(new.analysis.df$BookiesProbActualWinner[i])){
        spent <- spent + 1
        won <- won + new.analysis.df$AverageWinnerBOdds[i] 
      }
    } else {
      if (new.analysis.df$PredProbActualLoser[i] > as.numeric(new.analysis.df$BookiesProbActualLoser[i])){
        spent <- spent + 1
      }
    }
  }
  return((won-spent)*100/spent)
}

# Brier Scores
brier <- function(analysis.df){
  return(0.5*(((analysis.df$PredProbActualWinner - 1)^2)+((analysis.df$PredProbActualLoser)^2)))
}

# Average Brier Score
av.brier <- function(analysis.df){
  briers <- 0.5*(((analysis.df$PredProbActualWinner - 1)^2)+((analysis.df$PredProbActualLoser)^2))
  return(mean(briers))
}

# spherical Scores
spherical <- function(analysis.df){
  return(-1*(analysis.df$PredProbActualWinner)/(sqrt(analysis.df$PredProbActualWinner^2 + analysis.df$PredProbActualLoser^2)))
}

# Average Spherical Score
av.spherical <- function(analysis.df){
  sphericals <- -1*(analysis.df$PredProbActualWinner)/(sqrt(analysis.df$PredProbActualWinner^2 + analysis.df$PredProbActualLoser^2))
  return(mean(sphericals))
}
```

```{r}
# Logisitc Regression Using ATP RAnk HARD
N <- nrow(training.df.hard)
X.BT.hard <- rep(0,N)
ymat.BT.hard <- matrix(0, N, 2)

for (i in(1:N)){
  
  winner.BT.hard <- ifelse(training.df.hard$Winner[i] %in% hard$Players, hard$HardCourtStrength[which(hard$Players == training.df.hard$Winner[i])], min(as.numeric(hard$HardCourtStrength)))
  loser.BT.hard <- ifelse(training.df.hard$Loser[i] %in% hard$Players, hard$HardCourtStrength[which(hard$Players == training.df.hard$Loser[i])], min(as.numeric(hard$HardCourtStrength)))
  
  winner.BT.hard <- as.numeric(winner.BT.hard)
  loser.BT.hard <- as.numeric(loser.BT.hard)
  
  X.BT.hard[i] <- log(winner.BT.hard/loser.BT.hard)
  ymat.BT.hard[i,1] <- 1 
}

BT.fit.hard <- glm(ymat.BT.hard ~ 0 + X.BT.hard, family=binomial(link=logit))
summary(BT.fit.hard)
```

```{r}
M <- nrow(test.df.hard)
X.BT.test.hard <- rep(0,M)

for (i in (1:M)){
  winner.BT.test.hard <- ifelse(test.df.hard$Winner[i] %in% hard$Players, hard$HardCourtStrength[which(hard$Players == test.df.hard$Winner[i])], min(as.numeric(hard$HardCourtStrength)))
  loser.BT.test.hard <- ifelse(test.df.hard$Loser[i] %in% hard$Players, hard$HardCourtStrength[which(hard$Players == test.df.hard$Loser[i])], min(as.numeric(hard$HardCourtStrength)))
  
  winner.BT.test.hard <- as.numeric(winner.BT.test.hard)
  loser.BT.test.hard <- as.numeric(loser.BT.test.hard)
  
  X.BT.test.hard[i] <- log(winner.BT.test.hard/loser.BT.test.hard)
}
X.BT.test.hard <- as.data.frame(X.BT.test.hard)
colnames(X.BT.test.hard) <- 'X.BT.hard'

BT.fit.pred.hard <- predict(BT.fit.hard, newdata=X.BT.test.hard, type='response')
```

```{r}
# Produces Analysis Dataframe

  M <- nrow(test.df.hard)
  match.info <- c()

  for (i in (1:M)){
    
# Actual winner - our model does not know this is the winner
    winner = test.df.hard$Winner[i]
   
# Actual loser - our model does not know this is the loser
    loser = test.df.hard$Loser[i]
    
# Calculating the implied bookmaker probabilities
    winner.av.bodds <- (test.df.hard$B365W[i] + test.df.hard$EXW[i] + test.df.hard$LBW[i] + test.df.hard$PSW[i])/4
    winner.av.bprob <- 1/winner.av.bodds
    
    loser.av.bodds <- (test.df.hard$B365L[i] + test.df.hard$EXL[i] + test.df.hard$LBL[i] + test.df.hard$PSL[i])/4
    loser.av.bprob <- 1/loser.av.bodds
    
    winner.implied.bprob <- winner.av.bprob / (winner.av.bprob + loser.av.bprob)
    loser.implied.bprob <- loser.av.bprob / (winner.av.bprob + loser.av.bprob)
    
# Predicted probability that the actual winner wins
    pred.win.prob <- BT.fit.pred.hard[i]
    
# Predicted probability that the actual loser wins
    pred.lose.prob <- 1- pred.win.prob
    
# If the above two are the same, we chose a winner at random
    if (pred.win.prob == pred.lose.prob){
      pred.winner <- sample(c(winner,loser), 1, prob=c(0.5,0.5))
    } else {
      pred.winner <- ifelse(pred.win.prob > pred.lose.prob, winner, loser)
    }
    
  #pred.winner <- sample(c(winner,loser), 1, prob=c(pred.win.prob, pred.lose.prob))
    
# Returns value 1 if our prediction is correct.
    is.pred.right <- ifelse(winner == pred.winner, 1, 0)
    
# Stores the calculated value every match in a vector
    match.info <- c(match.info,winner.av.bodds,winner.implied.bprob, pred.win.prob, winner, is.pred.right, loser, pred.lose.prob, loser.implied.bprob, loser.av.bodds)
    
  }
  
# Turn the above vector into a dataframe  
  rank.analysis.df.hard <- as.data.frame(t(matrix(match.info, nrow = 9)))
  colnames(rank.analysis.df.hard) <- c('AverageWinnerBOdds','BookiesProbActualWinner','PredProbActualWinner','ActualWinner', 'IsPredRight','ActualLoser','PredProbActualLoser','BookiesProbActualLoser','AverageLoserBOdds')
  
  rank.analysis.df.hard$PredProbActualWinner = as.numeric(rank.analysis.df.hard$PredProbActualWinner)
  rank.analysis.df.hard$PredProbActualLoser = as.numeric(rank.analysis.df.hard$PredProbActualLoser)
  rank.analysis.df.hard$IsPredRight = as.numeric(rank.analysis.df.hard$IsPredRight)
  rank.analysis.df.hard$AverageWinnerBOdds = as.numeric(rank.analysis.df.hard$AverageWinnerBOdds)
  rank.analysis.df.hard$AverageLoserBOdds = as.numeric(rank.analysis.df.hard$AverageLoserBOdds)
  rank.analysis.df.hard$BookiesProbActualWinner = as.numeric(rank.analysis.df.hard$BookiesProbActualWinner)
  rank.analysis.df.hard$BookiesProbActualLoser = as.numeric(rank.analysis.df.hard$BookiesProbActualLoser)
```

```{r}
# Logisitc Regression Using ATP RAnk CLAY
N <- nrow(training.df.clay)
X.BT.clay <- rep(0,N)
ymat.BT.clay <- matrix(0, N, 2)

for (i in(1:N)){
  
  winner.BT.clay <- ifelse(training.df.clay$Winner[i] %in% clay$Players, clay$ClayCourtStrength[which(clay$Players == training.df.clay$Winner[i])], min(as.numeric(clay$ClayCourtStrength)))
  loser.BT.clay <- ifelse(training.df.clay$Loser[i] %in% clay$Players, clay$ClayCourtStrength[which(clay$Players == training.df.clay$Loser[i])], min(as.numeric(clay$ClayCourtStrength)))
  
  winner.BT.clay <- as.numeric(winner.BT.clay)
  loser.BT.clay <- as.numeric(loser.BT.clay)
  
  X.BT.clay[i] <- log(winner.BT.clay/loser.BT.clay)
  ymat.BT.clay[i,1] <- 1 
}

BT.fit.clay <- glm(ymat.BT.clay ~ 0 + X.BT.clay, family=binomial(link=logit))
summary(BT.fit.clay)
```

```{r}
M <- nrow(test.df.clay)
X.BT.test.clay <- rep(0,M)

for (i in (1:M)){
  winner.BT.test.clay <- ifelse(test.df.clay$Winner[i] %in% clay$Players, clay$ClayCourtStrength[which(clay$Players == test.df.clay$Winner[i])], min(as.numeric(clay$ClayCourtStrength)))
  loser.BT.test.clay <- ifelse(test.df.clay$Loser[i] %in% clay$Players, clay$ClayCourtStrength[which(clay$Players == test.df.clay$Loser[i])], min(as.numeric(clay$ClayCourtStrength)))
  
  winner.BT.test.clay <- as.numeric(winner.BT.test.clay)
  loser.BT.test.clay <- as.numeric(loser.BT.test.clay)
  
  X.BT.test.clay[i] <- log(winner.BT.test.clay/loser.BT.test.clay)
}
X.BT.test.clay <- as.data.frame(X.BT.test.clay)
colnames(X.BT.test.clay) <- 'X.BT.clay'

BT.fit.pred.clay <- predict(BT.fit.clay, newdata=X.BT.test.clay, type='response')
```

```{r}
# Produces Analysis Dataframe

  M <- nrow(test.df.clay)
  match.info <- c()

  for (i in (1:M)){
    
# Actual winner - our model does not know this is the winner
    winner = test.df.clay$Winner[i]
   
# Actual loser - our model does not know this is the loser
    loser = test.df.clay$Loser[i]
    
# Calculating the implied bookmaker probabilities
    winner.av.bodds <- (test.df.clay$B365W[i] + test.df.clay$EXW[i] + test.df.clay$LBW[i] + test.df.clay$PSW[i])/4
    winner.av.bprob <- 1/winner.av.bodds
    
    loser.av.bodds <- (test.df.clay$B365L[i] + test.df.clay$EXL[i] + test.df.clay$LBL[i] + test.df.clay$PSL[i])/4
    loser.av.bprob <- 1/loser.av.bodds
    
    winner.implied.bprob <- winner.av.bprob / (winner.av.bprob + loser.av.bprob)
    loser.implied.bprob <- loser.av.bprob / (winner.av.bprob + loser.av.bprob)
    
# Predicted probability that the actual winner wins
    pred.win.prob <- BT.fit.pred.clay[i]
    
# Predicted probability that the actual loser wins
    pred.lose.prob <- 1- pred.win.prob
    
# If the above two are the same, we chose a winner at random
    if (pred.win.prob == pred.lose.prob){
      pred.winner <- sample(c(winner,loser), 1, prob=c(0.5,0.5))
    } else {
      pred.winner <- ifelse(pred.win.prob > pred.lose.prob, winner, loser)
    }
    
  #pred.winner <- sample(c(winner,loser), 1, prob=c(pred.win.prob, pred.lose.prob))
    
# Returns value 1 if our prediction is correct.
    is.pred.right <- ifelse(winner == pred.winner, 1, 0)
    
# Stores the calculated value every match in a vector
    match.info <- c(match.info,winner.av.bodds,winner.implied.bprob, pred.win.prob, winner, is.pred.right, loser, pred.lose.prob, loser.implied.bprob, loser.av.bodds)
    
  }
  
# Turn the above vector into a dataframe  
  rank.analysis.df.clay <- as.data.frame(t(matrix(match.info, nrow = 9)))
  colnames(rank.analysis.df.clay) <- c('AverageWinnerBOdds','BookiesProbActualWinner','PredProbActualWinner','ActualWinner', 'IsPredRight','ActualLoser','PredProbActualLoser','BookiesProbActualLoser','AverageLoserBOdds')
  
  rank.analysis.df.clay$PredProbActualWinner = as.numeric(rank.analysis.df.clay$PredProbActualWinner)
  rank.analysis.df.clay$PredProbActualLoser = as.numeric(rank.analysis.df.clay$PredProbActualLoser)
  rank.analysis.df.clay$IsPredRight = as.numeric(rank.analysis.df.clay$IsPredRight)
  rank.analysis.df.clay$AverageWinnerBOdds = as.numeric(rank.analysis.df.clay$AverageWinnerBOdds)
  rank.analysis.df.clay$AverageLoserBOdds = as.numeric(rank.analysis.df.clay$AverageLoserBOdds)
  rank.analysis.df.clay$BookiesProbActualWinner = as.numeric(rank.analysis.df.clay$BookiesProbActualWinner)
  rank.analysis.df.clay$BookiesProbActualLoser = as.numeric(rank.analysis.df.clay$BookiesProbActualLoser)
```

```{r}
# Logisitc Regression Using ATP RAnk GRASS
N <- nrow(training.df.grass)
X.BT.grass <- rep(0,N)
ymat.BT.grass <- matrix(0, N, 2)

for (i in(1:N)){
  
  winner.BT.grass <- ifelse(training.df.grass$Winner[i] %in% grass$Players, grass$GrassCourtStrength[which(grass$Players == training.df.grass$Winner[i])], min(as.numeric(grass$GrassCourtStrength)))
  loser.BT.grass <- ifelse(training.df.grass$Loser[i] %in% grass$Players, grass$GrassCourtStrength[which(grass$Players == training.df.grass$Loser[i])], min(as.numeric(grass$GrassCourtStrength)))
  
  winner.BT.grass <- as.numeric(winner.BT.grass)
  loser.BT.grass <- as.numeric(loser.BT.grass)
  
  X.BT.grass[i] <- log(winner.BT.grass/loser.BT.grass)
  ymat.BT.grass[i,1] <- 1 
}

BT.fit.grass <- glm(ymat.BT.grass ~ 0 + X.BT.grass, family=binomial(link=logit))
summary(BT.fit.grass)
```

```{r}
M <- nrow(test.df.grass)
X.BT.test.grass <- rep(0,M)

for (i in (1:M)){
  winner.BT.test.grass <- ifelse(test.df.grass$Winner[i] %in% grass$Players, grass$GrassCourtStrength[which(grass$Players == test.df.grass$Winner[i])], min(as.numeric(grass$GrassCourtStrength)))
  loser.BT.test.grass <- ifelse(test.df.grass$Loser[i] %in% grass$Players, grass$GrassCourtStrength[which(grass$Players == test.df.grass$Loser[i])], min(as.numeric(grass$GrassCourtStrength)))
  
  winner.BT.test.grass <- as.numeric(winner.BT.test.grass)
  loser.BT.test.grass <- as.numeric(loser.BT.test.grass)
  
  X.BT.test.grass[i] <- log(winner.BT.test.grass/loser.BT.test.grass)
}
X.BT.test.grass<- as.data.frame(X.BT.test.grass)
colnames(X.BT.test.grass) <- 'X.BT.grass'

BT.fit.pred.grass <- predict(BT.fit.grass, newdata=X.BT.test.grass, type='response')
```

```{r}
# Produces Analysis Dataframe

  M <- nrow(test.df.grass)
  match.info <- c()

  for (i in (1:M)){
    
# Actual winner - our model does not know this is the winner
    winner = test.df.grass$Winner[i]
   
# Actual loser - our model does not know this is the loser
    loser = test.df.grass$Loser[i]
    
# Calculating the implied bookmaker probabilities
    winner.av.bodds <- (test.df.grass$B365W[i] + test.df.grass$EXW[i] + test.df.grass$LBW[i] + test.df.grass$PSW[i])/4
    winner.av.bprob <- 1/winner.av.bodds
    
    loser.av.bodds <- (test.df.grass$B365L[i] + test.df.grass$EXL[i] + test.df.grass$LBL[i] + test.df.grass$PSL[i])/4
    loser.av.bprob <- 1/loser.av.bodds
    
    winner.implied.bprob <- winner.av.bprob / (winner.av.bprob + loser.av.bprob)
    loser.implied.bprob <- loser.av.bprob / (winner.av.bprob + loser.av.bprob)
    
# Predicted probability that the actual winner wins
    pred.win.prob <- BT.fit.pred.grass[i]
    
# Predicted probability that the actual loser wins
    pred.lose.prob <- 1- pred.win.prob
    
# If the above two are the same, we chose a winner at random
    if (pred.win.prob == pred.lose.prob){
      pred.winner <- sample(c(winner,loser), 1, prob=c(0.5,0.5))
    } else {
      pred.winner <- ifelse(pred.win.prob > pred.lose.prob, winner, loser)
    }
    
  #pred.winner <- sample(c(winner,loser), 1, prob=c(pred.win.prob, pred.lose.prob))
    
# Returns value 1 if our prediction is correct.
    is.pred.right <- ifelse(winner == pred.winner, 1, 0)
    
# Stores the calculated value every match in a vector
    match.info <- c(match.info,winner.av.bodds,winner.implied.bprob, pred.win.prob, winner, is.pred.right, loser, pred.lose.prob, loser.implied.bprob, loser.av.bodds)
    
  }
  
# Turn the above vector into a dataframe  
  rank.analysis.df.grass <- as.data.frame(t(matrix(match.info, nrow = 9)))
  colnames(rank.analysis.df.grass) <- c('AverageWinnerBOdds','BookiesProbActualWinner','PredProbActualWinner','ActualWinner', 'IsPredRight','ActualLoser','PredProbActualLoser','BookiesProbActualLoser','AverageLoserBOdds')
  
  rank.analysis.df.grass$PredProbActualWinner = as.numeric(rank.analysis.df.grass$PredProbActualWinner)
  rank.analysis.df.grass$PredProbActualLoser = as.numeric(rank.analysis.df.grass$PredProbActualLoser)
  rank.analysis.df.grass$IsPredRight = as.numeric(rank.analysis.df.grass$IsPredRight)
  rank.analysis.df.grass$AverageWinnerBOdds = as.numeric(rank.analysis.df.grass$AverageWinnerBOdds)
  rank.analysis.df.grass$AverageLoserBOdds = as.numeric(rank.analysis.df.grass$AverageLoserBOdds)
  rank.analysis.df.grass$BookiesProbActualWinner = as.numeric(rank.analysis.df.grass$BookiesProbActualWinner)
  rank.analysis.df.grass$BookiesProbActualLoser = as.numeric(rank.analysis.df.grass$BookiesProbActualLoser)
```

```{r}
rank.analysis.df <- rbind(rank.analysis.df.hard, rank.analysis.df.clay)
rank.analysis.df <- rbind(rank.analysis.df, rank.analysis.df.grass)
```

```{r}
av.brier(rank.analysis.df)
av.log.win.prob(rank.analysis.df)
av.spherical(rank.analysis.df)
av.win.prob(rank.analysis.df)
pred.acc(rank.analysis.df)
roi(rank.analysis.df)
calibration(rank.analysis.df, 'BT.Magnus.KLassen.surface.cloglog')
```

```{r}
#Hosmer Lemeshaw
library(ResourceSelection)
fitted <- BT.fit.hard$fitted.values
actual <- ymat.BT.hard[,1]
hoslem.test(actual, fitted, g=10)
```

```{r}
#Hosmer Lemeshaw
library(ResourceSelection)
fitted <- BT.fit.clay$fitted.values
actual <- ymat.BT.clay[,1]
hoslem.test(actual, fitted, g=10)
```

```{r}
#Hosmer Lemeshaw
library(ResourceSelection)
fitted <- BT.fit.grass$fitted.values
actual <- ymat.BT.grass[,1]
hoslem.test(actual, fitted, g=10)
```